services:
  - type: web
    name: easyprivacy
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: SESSION_COOKIE_SECURE
        value: "true"
      - key: SESSION_COOKIE_SAMESITE
        value: "Lax"
      - key: FRONTEND_INDEX
        value: "index.html"
      - key: FRONTEND_STYLE
        value: "style.css"
